//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class JRodriguezExamenPracticoEnITmaEntities : DbContext
    {
        public JRodriguezExamenPracticoEnITmaEntities()
            : base("name=JRodriguezExamenPracticoEnITmaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Exa_CatalogoProducto> Exa_CatalogoProducto { get; set; }
    
        public virtual ObjectResult<GetAllCatalogoProd_Result> GetAllCatalogoProd()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllCatalogoProd_Result>("GetAllCatalogoProd");
        }
    
        public virtual int sp_InsCatalogoProd(string descripcion)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsCatalogoProd", descripcionParameter);
        }
    
        public virtual ObjectResult<GetByIdCatalogoProd_Result> GetByIdCatalogoProd(Nullable<int> idProducto)
        {
            var idProductoParameter = idProducto.HasValue ?
                new ObjectParameter("IdProducto", idProducto) :
                new ObjectParameter("IdProducto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetByIdCatalogoProd_Result>("GetByIdCatalogoProd", idProductoParameter);
        }
    
        public virtual int UpdateCatalogoProd(Nullable<int> idProducto, string descripcion)
        {
            var idProductoParameter = idProducto.HasValue ?
                new ObjectParameter("IdProducto", idProducto) :
                new ObjectParameter("IdProducto", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateCatalogoProd", idProductoParameter, descripcionParameter);
        }
    }
}
